name: 'Terraform Deploy'

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    # 1. Download your code
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. Log in to Azure (Using the Secret you saved)
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # 3. Install Terraform on the server
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    # 4. Connect to Remote Backend (The Brain)
    - name: Terraform Init
      run: terraform init

    # 5. Check for errors
    - name: Terraform Plan
      run: terraform plan

    # 6. Apply Changes (Auto-Approve for automation)
    - name: Terraform Apply
      run: terraform apply -auto-approve
